version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: codeblog

  adminer:
    image: adminer
    ports:
      - 8082:8082